// Mock for @wails/runtime/runtime used in tests
export const EventsOn = () => {}
export const EventsOff = () => {}
export const EventsOnce = () => {}
export const EventsOnMultiple = () => {}
export const EventsEmit = () => {}
export const LogDebug = () => {}
export const LogInfo = () => {}
export const LogWarning = () => {}
export const LogError = () => {}
export const WindowReload = () => {}
export const WindowSetDarkTheme = () => {}
export const WindowSetLightTheme = () => {}
export const WindowSetSystemDefaultTheme = () => {}
export const Environment = () => ({})
export const BrowserOpenURL = () => {}
export const Quit = () => {}
export const Show = () => {}
export const Hide = () => {}
export const WindowMinimise = () => {}
export const WindowIsMinimised = () => false
export const WindowToggleMaximise = () => {}
export const WindowIsMaximised = () => false
export const WindowCenter = () => {}
export const WindowSetSize = () => {}
export const WindowSetPosition = () => {}
export const WindowSetAlwaysOnTop = () => {}
export const WindowSetTitle = () => {}
export const ClipboardGetText = () => ''
export const ClipboardSetText = () => {}
