// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function AbsolutePath(arg1:string):Promise<bridge.FlagResult>;

export function CleanInvalidCloudNodes():Promise<bridge.FlagResult>;

export function CloseMMDB(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function CopyFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function CreateCloudInstance(arg1:string):Promise<bridge.FlagResult>;
export function CreateCloudInstanceTyped(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CreateMultipleCloudInstances(arg1:string):Promise<bridge.FlagResult>;
export function CreateMultipleCloudInstancesTyped(arg1:Array<Record<string, any>>):Promise<Array<Record<string, any>>>;

export function DestroyCloudInstance(arg1:string):Promise<bridge.FlagResult>;
export function DestroyCloudInstanceTyped(arg1:string):Promise<void>;

export function Download(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string,arg6:bridge.RequestOptions):Promise<bridge.HTTPResult>;

export function Exec(arg1:string,arg2:Array<string>,arg3:bridge.ExecOptions):Promise<bridge.FlagResult>;

export function ExecBackground(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:bridge.ExecOptions):Promise<bridge.FlagResult>;

export function ExitApp():Promise<void>;

export function FileExists(arg1:string):Promise<bridge.FlagResult>;

export function GetAvailablePort():Promise<number>;

export function GetCloudConfig():Promise<bridge.FlagResult>;
export function GetCloudConfigTyped():Promise<Record<string, any>>;

export function GetCloudProvider():Promise<bridge.FlagResult>;
export function GetCloudProviderTyped():Promise<Record<string, any>>;

export function GetEnv():Promise<bridge.EnvResult>;

export function GetLoadBalancerStatus():Promise<bridge.FlagResult>;

export function GetFastestCloudRegion():Promise<bridge.FlagResult>;

export function GetHealthStatus():Promise<bridge.FlagResult>;

export function GetInterfaces():Promise<bridge.FlagResult>;

export function IsStartup():Promise<boolean>;

export function KillProcess(arg1:number,arg2:number):Promise<bridge.FlagResult>;

export function ListCloudAvailability(arg1:string):Promise<bridge.FlagResult>;
export function ListCloudAvailabilityTyped(arg1:string):Promise<Array<string>>;

export function ListCloudInstances():Promise<bridge.FlagResult>;
export function ListCloudInstancesTyped():Promise<Array<Record<string, any>>>;

export function ListCloudPlans():Promise<bridge.FlagResult>;
export function ListCloudPlansTyped():Promise<Array<Record<string, any>>>;

export function ListCloudProviders():Promise<bridge.FlagResult>;
export function ListCloudProvidersTyped():Promise<Array<Record<string, any>>>;

export function ListCloudRegions():Promise<bridge.FlagResult>;
export function ListCloudRegionsTyped():Promise<Array<Record<string, any>>>;

export function ListServer():Promise<bridge.FlagResult>;

export function MakeDir(arg1:string):Promise<bridge.FlagResult>;

export function MoveFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function Notify(arg1:string,arg2:string,arg3:string,arg4:bridge.NotifyOptions):Promise<bridge.FlagResult>;

export function OpenMMDB(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function ProcessInfo(arg1:number):Promise<bridge.FlagResult>;

export function QueryMMDB(arg1:string,arg2:string,arg3:string):Promise<bridge.FlagResult>;

export function ReadDir(arg1:string):Promise<bridge.FlagResult>;

export function ReadFile(arg1:string,arg2:bridge.IOOptions):Promise<bridge.FlagResult>;

export function RemoveFile(arg1:string):Promise<bridge.FlagResult>;

export function Requests(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string,arg5:bridge.RequestOptions):Promise<bridge.HTTPResult>;

export function RestartApp():Promise<bridge.FlagResult>;

export function SaveCloudConfig(arg1:string):Promise<bridge.FlagResult>;
export function SaveCloudConfigTyped(arg1:Record<string, any>):Promise<void>;

export function ScoreCloudRegions(arg1:string):Promise<bridge.FlagResult>;

export function SetCloudProvider(arg1:string):Promise<bridge.FlagResult>;
export function SetCloudProviderTyped(arg1:string):Promise<Record<string, any>>;

export function SetupSSHEventEmitter():Promise<void>;

export function ShowMainWindow():Promise<void>;

export function StartHealthMonitor():Promise<bridge.FlagResult>;

export function StartLoadBalancer(arg1:number,arg2:string):Promise<bridge.FlagResult>;

export function StopLoadBalancer():Promise<bridge.FlagResult>;

export function StartServer(arg1:string,arg2:string,arg3:bridge.ServerOptions):Promise<bridge.FlagResult>;

export function StopHealthMonitor():Promise<bridge.FlagResult>;

export function StopServer(arg1:string):Promise<bridge.FlagResult>;

export function TestAllCloudRegions():Promise<bridge.FlagResult>;

export function TestCloudRegionLatency(arg1:string):Promise<bridge.FlagResult>;

export function TestConnectivity(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function TestDownloadSpeed(arg1:string,arg2:string,arg3:number):Promise<bridge.FlagResult>;

export function TestNodeDirectSpeed(arg1:string,arg2:number):Promise<bridge.FlagResult>;

export function TestNodeSpeed(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function TestSSHConnection(arg1:string):Promise<bridge.FlagResult>;
export function TestSSHConnectionTyped(arg1:Record<string, string>):Promise<Record<string, any>>;

export function UnzipGZFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function UnzipTarGZFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function UnzipZIPFile(arg1:string,arg2:string):Promise<bridge.FlagResult>;

export function UpdateTray(arg1:bridge.TrayContent):Promise<void>;

export function UpdateTrayMenus(arg1:Array<bridge.MenuItem>):Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string,arg6:bridge.RequestOptions):Promise<bridge.HTTPResult>;

export function WriteFile(arg1:string,arg2:string,arg3:bridge.IOOptions):Promise<bridge.FlagResult>;
