// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbsolutePath(arg1) {
  return window['go']['bridge']['App']['AbsolutePath'](arg1);
}

export function CleanInvalidCloudNodes() {
  return window['go']['bridge']['App']['CleanInvalidCloudNodes']();
}

export function ClearCdn() {
  return window['go']['bridge']['App']['ClearCdn']();
}

export function ClearCdnCustomDomain() {
  return window['go']['bridge']['App']['ClearCdnCustomDomain']();
}

export function ClearCdnCustomDomainTyped() {
  return window['go']['bridge']['App']['ClearCdnCustomDomainTyped']();
}

export function ClearCdnTyped() {
  return window['go']['bridge']['App']['ClearCdnTyped']();
}

export function CloseMMDB(arg1, arg2) {
  return window['go']['bridge']['App']['CloseMMDB'](arg1, arg2);
}

export function CopyFile(arg1, arg2) {
  return window['go']['bridge']['App']['CopyFile'](arg1, arg2);
}

export function CreateCloudInstance(arg1) {
  return window['go']['bridge']['App']['CreateCloudInstance'](arg1);
}

export function CreateCloudInstanceTyped(arg1) {
  return window['go']['bridge']['App']['CreateCloudInstanceTyped'](arg1);
}

export function CreateMultipleCloudInstances(arg1) {
  return window['go']['bridge']['App']['CreateMultipleCloudInstances'](arg1);
}

export function CreateMultipleCloudInstancesTyped(arg1) {
  return window['go']['bridge']['App']['CreateMultipleCloudInstancesTyped'](arg1);
}

export function DeleteCdnWorkerForNode(arg1) {
  return window['go']['bridge']['App']['DeleteCdnWorkerForNode'](arg1);
}

export function DeleteCdnWorkerForNodeTyped(arg1) {
  return window['go']['bridge']['App']['DeleteCdnWorkerForNodeTyped'](arg1);
}

export function DeployCdnWorkerForNode(arg1) {
  return window['go']['bridge']['App']['DeployCdnWorkerForNode'](arg1);
}

export function DeployCdnWorkerForNodeTyped(arg1) {
  return window['go']['bridge']['App']['DeployCdnWorkerForNodeTyped'](arg1);
}

export function DestroyCloudInstance(arg1) {
  return window['go']['bridge']['App']['DestroyCloudInstance'](arg1);
}

export function DestroyCloudInstanceTyped(arg1) {
  return window['go']['bridge']['App']['DestroyCloudInstanceTyped'](arg1);
}

export function DiagnoseSingbox() {
  return window['go']['bridge']['App']['DiagnoseSingbox']();
}

export function Download(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['bridge']['App']['Download'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Exec(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['Exec'](arg1, arg2, arg3);
}

export function ExecBackground(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['ExecBackground'](arg1, arg2, arg3, arg4, arg5);
}

export function ExitApp() {
  return window['go']['bridge']['App']['ExitApp']();
}

export function ExportCloudBackup(arg1) {
  return window['go']['bridge']['App']['ExportCloudBackup'](arg1);
}

export function FileExists(arg1) {
  return window['go']['bridge']['App']['FileExists'](arg1);
}

export function GetAvailablePort() {
  return window['go']['bridge']['App']['GetAvailablePort']();
}

export function GetCdnState() {
  return window['go']['bridge']['App']['GetCdnState']();
}

export function GetCdnStateTyped() {
  return window['go']['bridge']['App']['GetCdnStateTyped']();
}

export function GetCloudConfig() {
  return window['go']['bridge']['App']['GetCloudConfig']();
}

export function GetCloudConfigTyped() {
  return window['go']['bridge']['App']['GetCloudConfigTyped']();
}

export function GetCloudProvider() {
  return window['go']['bridge']['App']['GetCloudProvider']();
}

export function GetCloudProviderAccountStatus(arg1) {
  return window['go']['bridge']['App']['GetCloudProviderAccountStatus'](arg1);
}

export function GetCloudProviderAccountStatusTyped(arg1) {
  return window['go']['bridge']['App']['GetCloudProviderAccountStatusTyped'](arg1);
}

export function GetCloudProviderTyped() {
  return window['go']['bridge']['App']['GetCloudProviderTyped']();
}

export function GetEnv() {
  return window['go']['bridge']['App']['GetEnv']();
}

export function GetFastestCloudRegion() {
  return window['go']['bridge']['App']['GetFastestCloudRegion']();
}

export function GetHealthStatus() {
  return window['go']['bridge']['App']['GetHealthStatus']();
}

export function GetInterfaces() {
  return window['go']['bridge']['App']['GetInterfaces']();
}

export function GetLoadBalancerStatus() {
  return window['go']['bridge']['App']['GetLoadBalancerStatus']();
}

export function ImportCloudBackup() {
  return window['go']['bridge']['App']['ImportCloudBackup']();
}

export function IsStartup() {
  return window['go']['bridge']['App']['IsStartup']();
}

export function KillOrphanCores() {
  return window['go']['bridge']['App']['KillOrphanCores']();
}

export function KillProcess(arg1, arg2) {
  return window['go']['bridge']['App']['KillProcess'](arg1, arg2);
}

export function ListCdnZones() {
  return window['go']['bridge']['App']['ListCdnZones']();
}

export function ListCdnZonesTyped() {
  return window['go']['bridge']['App']['ListCdnZonesTyped']();
}

export function ListCloudAvailability(arg1) {
  return window['go']['bridge']['App']['ListCloudAvailability'](arg1);
}

export function ListCloudAvailabilityTyped(arg1) {
  return window['go']['bridge']['App']['ListCloudAvailabilityTyped'](arg1);
}

export function ListCloudInstances() {
  return window['go']['bridge']['App']['ListCloudInstances']();
}

export function ListCloudInstancesTyped() {
  return window['go']['bridge']['App']['ListCloudInstancesTyped']();
}

export function ListCloudPlans() {
  return window['go']['bridge']['App']['ListCloudPlans']();
}

export function ListCloudPlansTyped() {
  return window['go']['bridge']['App']['ListCloudPlansTyped']();
}

export function ListCloudProviders() {
  return window['go']['bridge']['App']['ListCloudProviders']();
}

export function ListCloudProvidersTyped() {
  return window['go']['bridge']['App']['ListCloudProvidersTyped']();
}

export function ListCloudRegions() {
  return window['go']['bridge']['App']['ListCloudRegions']();
}

export function ListCloudRegionsTyped() {
  return window['go']['bridge']['App']['ListCloudRegionsTyped']();
}

export function ListServer() {
  return window['go']['bridge']['App']['ListServer']();
}

export function MakeDir(arg1) {
  return window['go']['bridge']['App']['MakeDir'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['bridge']['App']['MoveFile'](arg1, arg2);
}

export function Notify(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['Notify'](arg1, arg2, arg3, arg4);
}

export function OpenMMDB(arg1, arg2) {
  return window['go']['bridge']['App']['OpenMMDB'](arg1, arg2);
}

export function ProcessInfo(arg1) {
  return window['go']['bridge']['App']['ProcessInfo'](arg1);
}

export function QueryMMDB(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['QueryMMDB'](arg1, arg2, arg3);
}

export function ReadDir(arg1) {
  return window['go']['bridge']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1, arg2) {
  return window['go']['bridge']['App']['ReadFile'](arg1, arg2);
}

export function RemoveFile(arg1) {
  return window['go']['bridge']['App']['RemoveFile'](arg1);
}

export function RepairCloudInstance(arg1) {
  return window['go']['bridge']['App']['RepairCloudInstance'](arg1);
}

export function RepairCloudInstanceTyped(arg1) {
  return window['go']['bridge']['App']['RepairCloudInstanceTyped'](arg1);
}

export function Requests(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['Requests'](arg1, arg2, arg3, arg4, arg5);
}

export function RestartApp() {
  return window['go']['bridge']['App']['RestartApp']();
}

export function SaveCloudConfig(arg1) {
  return window['go']['bridge']['App']['SaveCloudConfig'](arg1);
}

export function SaveCloudConfigTyped(arg1) {
  return window['go']['bridge']['App']['SaveCloudConfigTyped'](arg1);
}

export function ScoreCloudRegions(arg1) {
  return window['go']['bridge']['App']['ScoreCloudRegions'](arg1);
}

export function SetCdnCustomDomain(arg1, arg2) {
  return window['go']['bridge']['App']['SetCdnCustomDomain'](arg1, arg2);
}

export function SetCdnCustomDomainTyped(arg1, arg2) {
  return window['go']['bridge']['App']['SetCdnCustomDomainTyped'](arg1, arg2);
}

export function SetCloudProvider(arg1) {
  return window['go']['bridge']['App']['SetCloudProvider'](arg1);
}

export function SetCloudProviderTyped(arg1) {
  return window['go']['bridge']['App']['SetCloudProviderTyped'](arg1);
}

export function SetupSSHEventEmitter() {
  return window['go']['bridge']['App']['SetupSSHEventEmitter']();
}

export function ShowMainWindow() {
  return window['go']['bridge']['App']['ShowMainWindow']();
}

export function StartHealthMonitor() {
  return window['go']['bridge']['App']['StartHealthMonitor']();
}

export function StartLoadBalancer(arg1, arg2) {
  return window['go']['bridge']['App']['StartLoadBalancer'](arg1, arg2);
}

export function StartServer(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['StartServer'](arg1, arg2, arg3);
}

export function StopHealthMonitor() {
  return window['go']['bridge']['App']['StopHealthMonitor']();
}

export function StopLoadBalancer() {
  return window['go']['bridge']['App']['StopLoadBalancer']();
}

export function StopServer(arg1) {
  return window['go']['bridge']['App']['StopServer'](arg1);
}

export function TestAllCloudRegions() {
  return window['go']['bridge']['App']['TestAllCloudRegions']();
}

export function TestCloudRegionLatency(arg1) {
  return window['go']['bridge']['App']['TestCloudRegionLatency'](arg1);
}

export function TestConnectivity(arg1, arg2) {
  return window['go']['bridge']['App']['TestConnectivity'](arg1, arg2);
}

export function TestDownloadSpeed(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['TestDownloadSpeed'](arg1, arg2, arg3);
}

export function TestNodeDirectSpeed(arg1, arg2) {
  return window['go']['bridge']['App']['TestNodeDirectSpeed'](arg1, arg2);
}

export function TestNodeSpeed(arg1, arg2) {
  return window['go']['bridge']['App']['TestNodeSpeed'](arg1, arg2);
}

export function TestSSHConnection(arg1) {
  return window['go']['bridge']['App']['TestSSHConnection'](arg1);
}

export function TestSSHConnectionTyped(arg1) {
  return window['go']['bridge']['App']['TestSSHConnectionTyped'](arg1);
}

export function UnzipGZFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipGZFile'](arg1, arg2);
}

export function UnzipTarGZFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipTarGZFile'](arg1, arg2);
}

export function UnzipZIPFile(arg1, arg2) {
  return window['go']['bridge']['App']['UnzipZIPFile'](arg1, arg2);
}

export function UpdateTray(arg1) {
  return window['go']['bridge']['App']['UpdateTray'](arg1);
}

export function UpdateTrayMenus(arg1) {
  return window['go']['bridge']['App']['UpdateTrayMenus'](arg1);
}

export function Upload(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['bridge']['App']['Upload'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function VerifyCdnToken(arg1) {
  return window['go']['bridge']['App']['VerifyCdnToken'](arg1);
}

export function VerifyCdnTokenTyped(arg1) {
  return window['go']['bridge']['App']['VerifyCdnTokenTyped'](arg1);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['WriteFile'](arg1, arg2, arg3);
}
